### ISSUE TITLE
mcp6002 Vss, Vdd wiring in pcb

### ISSUE THREAD

**Issue by b2unit69** [Testbild-synth/HAGIWO-029-033-Eurorack-quantizer#5]
please check mcp6002 pin4(Vss), pin8(Vdd) connection. 
pin4(Vss) is connected 5v and pin8(Vdd) is connected GND in PCB. is this right? let me know..

**Comment by b2unit69** [comment]
situation: using 5v from case power supply without 7805
now I can hear sound but don't know well about tunning.

![wiring-01](https://github.com/Testbild-synth/HAGIWO-029-033-Eurorack-quantizer/assets/38415863/bc6109b4-be7e-44e5-8731-95eeef1a9487)

**Comment by Testbild-synth** [comment]
you are correct. This was an issue with the first batch of pcbs which I thought I fixed years ago but turns out I never really uploaded the files (shame on me).
Sorry you had to go through the build process with a broken pcb and thanks for reminding, I uploaded new files that should reflect the correct orientation.
